uwsgi: 
  socket: /tmp/uwsgi.sock
  pidfile: /var/run/flaskwalkthrough_uwsgi.pid
  daemonize: /home/flaskwalkthrough/projects/flaskwalkthrough/log/app.log
  master: true
  processes: 1
  uid: flaskwalkthrough
  gid: flaskwalkthrough
  wsgi-file: /home/flaskwalkthrough/projects/flaskwalkthrough/uwsgi_server.py
  callable: app
  touch-reload: /home/flaskwalkthrough/projects/flaskwalkthrough/tmp/restart.txt
