uwsgi: 
  socket: /tmp/uwsgi.sock
  pidfile: /var/run/flaskwalkthrough_uwsgi.pid
  daemonize: /home/administrator/projects/flask-walkthrough/log/app.log
  master: true
  processes: 1
  uid: administrator
  gid: administrator
  wsgi-file: /home/administrator/projects/flask-walkthrough/uwsgi_server.py
  callable: app
  touch-reload: /home/administrator/projects/flask-walkthrough/tmp/restart.txt
